# Support Vector Machines (SVMs) using scikit-learn in Python - Project Overview
### Let's tain and deploy SVMs on another dataset from UCI Machine Learning Repository 
### [Statlog (Australian Credit Approval) Data Set ](https://archive.ics.uci.edu/ml/datasets/Statlog+%28Australian+Credit+Approval%29)<br>

This real dataset concerns credit card applications. All attribute names and values have been changed to meaningless symbols to protect confidentiality of the data. <br>

You can download the datafile from the UCI website or use the one which is processed and provided in the course material. Later on, you can download the file from UCI website and do the data cleaning your self for practice your skills. <br>

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

**Read the datafile and display the head of your dataframe**

In [3]:
#Code here please, so that you dont lose the output
path = "Aust_Credit_Approval_Data.csv"
df = pd.read_csv(path)
df.head()

      x1     x2  x3  x4  x5     x6  x7  x8  x9  x10  x11  x12   x13  target
0  22.08  11.46   2   4   4  1.585   0   0   0    1    2  100  1213       0
1  22.67   7.00   2   8   4  0.165   0   0   0    0    2  160     1       0
2  29.58   1.75   1   4   4  1.250   0   0   0    1    2  280     1       0
3  21.67  11.50   1   5   3  0.000   1   1  11    1    2    0     1       1
4  20.17   8.17   2   6   4  1.960   1   1  14    0    2   60   159       1

        x1      x2  x3  x4  x5     x6  x7  x8  x9  x10  x11  x12   x13  target
0    22.08  11.460   2   4   4  1.585   0   0   0    1    2  100  1213       0
1    22.67   7.000   2   8   4  0.165   0   0   0    0    2  160     1       0
2    29.58   1.750   1   4   4  1.250   0   0   0    1    2  280     1       0
3    21.67  11.500   1   5   3  0.000   1   1  11    1    2    0     1       1
4    20.17   8.170   2   6   4  1.960   1   1  14    0    2   60   159       1
..     ...     ...  ..  ..  ..    ...  ..  ..  ..  ...  ...  ...   ...     ...
685  31.57  10.500   2  14   4  6.500   1   0   0    0    2    0     1       1
686  20.67   0.415   2   8   4  0.125   0   0   0    0    2    0    45       0
687  18.83   9.540   2   6   4  0.085   1   0   0    0    2  100     1       1
688  27.42  14.500   2  14   8  3.085   1   1   1    0    2  120    12       1
689  41.00   0.040   2  10   4  0.040   0   1   1    0    1  560     1       1

[690 rows x 14 columns]

In [9]:
#Code here please, so that you dont lose the output
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x1      690 non-null    float64
 1   x2      690 non-null    float64
 2   x3      690 non-null    int64
 3   x4      690 non-null    int64
 4   x5      690 non-null    int64
 5   x6      690 non-null    float64
 6   x7      690 non-null    int64
 7   x8      690 non-null    int64
 8   x9      690 non-null    int64
 9   x10     690 non-null    int64
 10  x11     690 non-null    int64
 11  x12     690 non-null    int64
 12  x13     690 non-null    int64
 13  target  690 non-null    int64
dtypes: float64(3), int64(11)
memory usage: 75.6 KB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 14 columns):
x1        690 non-null float64
x2        690 non-null float64
x3        690 non-null int64
x4        690 non-null int64
x5        690 non-null int64
x6        690 non-null float64
x7        690 non-null int64
x8        690 non-null int64
x9        690 non-null int64
x10       690 non-null int64
x11       690 non-null int64
x12       690 non-null int64
x13       690 non-null int64
target    690 non-null int64
dtypes: float64(3), int64(11)
memory usage: 75.5 KB

In [14]:
#Code here please, so that you dont lose the output
df = pd.read_csv("Aust_Credit_Approval_Data.csv", na_values=["?", "NA", "na", "null", "Null"])
df.describe()

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,target
count,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.00000,690.000000,690.000000,690.000000,690.000000,690.000000
mean,31.568203,4.758725,1.766667,7.372464,4.692754,2.223406,0.523188,0.427536,2.40000,0.457971,1.928986,184.014493,1018.385507,0.444928
std,11.853273,4.978163,0.430063,3.683265,1.992316,3.346513,0.499824,0.495080,4.86294,0.498592,0.298813,172.159274,5210.102598,0.497318
min,13.750000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,1.000000,0.000000,1.000000,0.000000
25%,22.670000,1.000000,2.000000,4.000000,4.000000,0.165000,0.000000,0.000000,0.00000,0.000000,2.000000,80.000000,1.000000,0.000000
50%,28.625000,2.750000,2.000000,8.000000,4.000000,1.000000,1.000000,0.000000,0.00000,0.000000,2.000000,160.000000,6.000000,0.000000
75%,37.707500,7.207500,2.000000,10.000000,5.000000,2.625000,1.000000,1.000000,3.00000,1.000000,2.000000,272.000000,396.500000,1.000000
max,80.250000,28.000000,3.000000,14.000000,9.000000,28.500000,1.000000,1.000000,67.00000,1.000000,3.000000,2000.000000,100001.000000,1.000000

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,target
count,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.00000,690.000000,690.000000,690.000000,690.000000,690.000000
mean,31.568203,4.758725,1.766667,7.372464,4.692754,2.223406,0.523188,0.427536,2.40000,0.457971,1.928986,184.014493,1018.385507,0.444928
std,11.853273,4.978163,0.430063,3.683265,1.992316,3.346513,0.499824,0.495080,4.86294,0.498592,0.298813,172.159274,5210.102598,0.497318
min,13.750000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,1.000000,0.000000,1.000000,0.000000
25%,22.670000,1.000000,2.000000,4.000000,4.000000,0.165000,0.000000,0.000000,0.00000,0.000000,2.000000,80.000000,1.000000,0.000000
50%,28.625000,2.750000,2.000000,8.000000,4.000000,1.000000,1.000000,0.000000,0.00000,0.000000,2.000000,160.000000,6.000000,0.000000
75%,37.707500,7.207500,2.000000,10.000000,5.000000,2.625000,1.000000,1.000000,3.00000,1.000000,2.000000,272.000000,396.500000,1.000000
max,80.250000,28.000000,3.000000,14.000000,9.000000,28.500000,1.000000,1.000000,67.00000,1.000000,3.000000,2000.000000,100001.000000,1.000000

Let's move on to machine learning. 
## Machine Learning

**split the features & target**

In [30]:
#Code here please, so that you dont lose the output
df = pd.read_csv("Aust_Credit_Approval_Data.csv")
X = df.drop(columns=["target"])
y = df["target"] 
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (690, 13)
y shape: (690,)

In [31]:
X

        x1      x2  x3  x4  x5     x6  x7  x8  x9  x10  x11  x12   x13
0    22.08  11.460   2   4   4  1.585   0   0   0    1    2  100  1213
1    22.67   7.000   2   8   4  0.165   0   0   0    0    2  160     1
2    29.58   1.750   1   4   4  1.250   0   0   0    1    2  280     1
3    21.67  11.500   1   5   3  0.000   1   1  11    1    2    0     1
4    20.17   8.170   2   6   4  1.960   1   1  14    0    2   60   159
..     ...     ...  ..  ..  ..    ...  ..  ..  ..  ...  ...  ...   ...
685  31.57  10.500   2  14   4  6.500   1   0   0    0    2    0     1
686  20.67   0.415   2   8   4  0.125   0   0   0    0    2    0    45
687  18.83   9.540   2   6   4  0.085   1   0   0    0    2  100     1
688  27.42  14.500   2  14   8  3.085   1   1   1    0    2  120    12
689  41.00   0.040   2  10   4  0.040   0   1   1    0    1  560     1

[690 rows x 13 columns]

        x1      x2  x3  x4  x5     x6  x7  x8  x9  x10  x11  x12   x13
0    22.08  11.460   2   4   4  1.585   0   0   0    1    2  100  1213
1    22.67   7.000   2   8   4  0.165   0   0   0    0    2  160     1
2    29.58   1.750   1   4   4  1.250   0   0   0    1    2  280     1
3    21.67  11.500   1   5   3  0.000   1   1  11    1    2    0     1
4    20.17   8.170   2   6   4  1.960   1   1  14    0    2   60   159
..     ...     ...  ..  ..  ..    ...  ..  ..  ..  ...  ...  ...   ...
685  31.57  10.500   2  14   4  6.500   1   0   0    0    2    0     1
686  20.67   0.415   2   8   4  0.125   0   0   0    0    2    0    45
687  18.83   9.540   2   6   4  0.085   1   0   0    0    2  100     1
688  27.42  14.500   2  14   8  3.085   1   1   1    0    2  120    12
689  41.00   0.040   2  10   4  0.040   0   1   1    0    1  560     1

[690 rows x 13 columns]

In [16]:
#Code here please, so that you dont lose the output
with pd.option_context("display.max_rows", 10):
    print(y)

0      0
1      0
2      0
3      1
4      1
      ..
685    1
686    0
687    1
688    1
689    1
Name: target, Length: 690, dtype: int64

0      0
1      0
2      0
3      1
4      1
      ..
685    1
686    0
687    1
688    1
689    1
Name: target, Length: 690, dtype: int64

**split the train & test (70% Train data, 30% test data)**

In [29]:
#Code here please, so that you dont lose the output
df = pd.read_csv("Aust_Credit_Approval_Data.csv")
X = df.drop(columns=["target"])
y = df["target"].astype(int)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)
print("Train shapes:", X_train.shape, y_train.shape)
print("Test shapes:",  X_test.shape,  y_test.shape)

Train shapes: (483, 13) (483,)
Test shapes: (207, 13) (207,)

In [19]:
X_train

        x1      x2  x3  x4  x5     x6  x7  x8  x9  x10  x11  x12   x13
19   22.42   5.665   2  11   4  2.585   1   1   7    0    2  129  3258
482  20.42   0.000   2   8   4  0.000   0   0   0    0    3  184     1
101  38.67   0.210   2   4   4  0.085   1   0   0    1    2  280     1
398  23.25  12.625   2   8   4  0.125   0   1   2    0    2    0  5553
311  49.00   1.500   2   5   3  0.000   1   0   0    1    2  100    28
..     ...     ...  ..  ..  ..    ...  ..  ..  ..  ...  ...  ...   ...
469  23.58  11.500   1   4   8  3.000   0   0   0    1    2   20    17
411  21.08   5.000   1   1   1  0.000   0   0   0    0    2    0     1
385  28.92  15.000   2   8   8  5.335   1   1  11    0    2    0  2284
422  29.83   1.250   1   4   4  0.250   0   0   0    0    2  224     1
28   30.67  12.000   2   8   4  2.000   1   1   1    0    2  220    20

[483 rows x 13 columns]

In [28]:
X_train

        x1      x2  x3  x4  x5     x6  x7  x8  x9  x10  x11  x12   x13
19   22.42   5.665   2  11   4  2.585   1   1   7    0    2  129  3258
482  20.42   0.000   2   8   4  0.000   0   0   0    0    3  184     1
101  38.67   0.210   2   4   4  0.085   1   0   0    1    2  280     1
398  23.25  12.625   2   8   4  0.125   0   1   2    0    2    0  5553
311  49.00   1.500   2   5   3  0.000   1   0   0    1    2  100    28
..     ...     ...  ..  ..  ..    ...  ..  ..  ..  ...  ...  ...   ...
469  23.58  11.500   1   4   8  3.000   0   0   0    1    2   20    17
411  21.08   5.000   1   1   1  0.000   0   0   0    0    2    0     1
385  28.92  15.000   2   8   8  5.335   1   1  11    0    2    0  2284
422  29.83   1.250   1   4   4  0.250   0   0   0    0    2  224     1
28   30.67  12.000   2   8   4  2.000   1   1   1    0    2  220    20

[483 rows x 13 columns]

### Importing and  training the Support Vector Classifier

**Import SVC and create its instance `svm_model`. Not required to find the best param to avoid complexity**

In [26]:
#Code here please, so that you dont lose the output
svm_model = SVC(C=20, gamma="auto", kernel="linear")
svm_model

SVC(C=20, gamma='auto', kernel='linear')

SVC(C=20, gamma='auto', kernel='linear')

**Find the model Score**

In [35]:
#Code here please, so that you dont lose the output
df = pd.read_csv("Aust_Credit_Approval_Data.csv")
X = df.drop(columns=["target"])
y = df["target"].astype(int)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=1, shuffle=True 
)
svm_model = SVC(C=20, gamma="auto", kernel="linear")
svm_model.fit(X_train, y_train)
print("Train score (accuracy):", svm_model.score(X_train, y_train))
print("Test score  (accuracy):", svm_model.score(X_test, y_test))

Train score (accuracy): 0.8695652173913043
Test score  (accuracy): 0.8454106280193237

0.8454106280193237

The model is improved after GridSearch but the prediction are not great. In the profession setup, you try different strategies including feature engineering along with using different models to see which one works best for your data. This section is specifically for the SVMs to learn how the model work and how to improve its performance.
# Excellent work!